Supprimer le numéro dans l'affichage du dossier patient
cnmh/app pull request #271
Opened 2024-01-13 10:06 UTC by Jalil-Betroji

2024-01-13 11:44 UTC, boukharSoufiane1998 approved these changes

2024-01-17 12:00 UTC, Yasmine-daifane approved these changes

2024-01-17 12:01 UTC, Yasmine-daifane approved these changes

2024-01-17 12:10 UTC, Yasmine-daifane approved these changes

2024-01-17 13:01 UTC, essarraj-fouad requested changes
Vous devez revalider l'issue sur

2024-01-19 13:13 UTC, merged