autorisation-pour-modifier-consultation-par-service-medical
cnmh/app pull request #273
Opened 2024-01-13 11:10 UTC by Jalil-Betroji

2024-01-13 11:49 UTC, boukharSoufiane1998 requested changes
Autorisation doit changer en maintenance base donnée ne pas dans Userseeder
- Creer une nouvelle class dans seeder maintenance_1_1_4 et attribuer la permission a user

2024-01-13 12:57 UTC, boukharSoufiane1998 approved these changes

2024-01-13 22:27 UTC, boukharSoufiane1998 approved these changes

2024-01-16 14:47 UTC, Yasmine-daifane approved these changes

2024-01-16 15:09 UTC, merged