Fix/consultation close #263, close #255
cnmh/app pull request #275
Opened 2024-01-13 13:09 UTC by boukharSoufiane1998

2024-01-13 13:16 UTC, Jalil-Betroji approved these changes

2024-01-17 10:08 UTC, Yasmine-daifane requested changes
the first bug is not solving : Undefined variable $tuteur  still  in

2024-01-17 10:26 UTC, Yasmine-daifane approved these changes

2024-01-17 10:26 UTC, Yasmine-daifane approved these changes

2024-01-17 10:59 UTC, Yasmine-daifane approved these changes

2024-01-17 10:59 UTC, Yasmine-daifane approved these changes

2024-01-17 11:27 UTC, Yasmine-daifane requested changes
the pull request should be related to one issue of bug  . in this PR u did fixed  three issus in one pull request

2024-01-17 11:30 UTC, closed without merging